'use strict';
/**
 * Seed catalogue: categories, brands and products for Biahens Enterprise.
 * Prices are in Ghana Cedis and reflect typical Accra market pricing.
 */

const CATEGORIES = [
  { name: 'Phones & Tablets', slug: 'phones-tablets', icon: '📱', accent: '#1E5C7A', children: [
    { name: 'Smartphones', slug: 'smartphones' },
    { name: 'Feature Phones', slug: 'feature-phones' },
    { name: 'Tablets', slug: 'tablets' },
    { name: 'Phone Accessories', slug: 'phone-accessories' },
    { name: 'Refurbished Phones', slug: 'refurbished-phones' },
  ] },
  { name: 'Electronics', slug: 'electronics', icon: '🔌', accent: '#3A5A78', children: [
    { name: 'TV & Video', slug: 'tv-video' },
    { name: 'Audio & Headphones', slug: 'audio-headphones' },
    { name: 'Cameras & Drones', slug: 'cameras-drones' },
    { name: 'Gaming', slug: 'gaming' },
    { name: 'Smart Wearables', slug: 'smart-wearables' },
  ] },
  { name: 'Computing', slug: 'computing', icon: '💻', accent: '#2F5D7C', children: [
    { name: 'Laptops', slug: 'laptops' },
    { name: 'Desktops & All-in-One', slug: 'desktops' },
    { name: 'Monitors', slug: 'monitors' },
    { name: 'Printers & Scanners', slug: 'printers' },
    { name: 'Storage & Networking', slug: 'storage-networking' },
    { name: 'Laptop Accessories', slug: 'laptop-accessories' },
  ] },
  { name: 'Fashion', slug: 'fashion', icon: '👗', accent: '#6E2B45', children: [
    { name: "Men's Clothing", slug: 'mens-clothing' },
    { name: "Women's Clothing", slug: 'womens-clothing' },
    { name: 'Traditional & Kente Wear', slug: 'traditional-wear' },
    { name: 'Kids & Baby', slug: 'kids-baby' },
    { name: 'Watches & Jewellery', slug: 'watches-jewellery' },
  ] },
  { name: 'Shoes & Bags', slug: 'shoes-bags', icon: '👟', accent: '#7A5B1E', children: [
    { name: 'Sneakers & Trainers', slug: 'sneakers' },
    { name: 'Formal & Office Shoes', slug: 'formal-shoes' },
    { name: 'Sandals & Slippers', slug: 'sandals-slippers' },
    { name: 'Handbags & Totes', slug: 'handbags' },
    { name: 'Backpacks & Luggage', slug: 'backpacks-luggage' },
  ] },
  { name: 'Home & Kitchen', slug: 'home-kitchen', icon: '🏠', accent: '#14624A', children: [
    { name: 'Cookware & Dining', slug: 'cookware' },
    { name: 'Small Kitchen Appliances', slug: 'kitchen-appliances' },
    { name: 'Furniture', slug: 'furniture' },
    { name: 'Bedding & Bath', slug: 'bedding-bath' },
    { name: 'Home Décor', slug: 'home-decor' },
  ] },
  { name: 'Appliances', slug: 'appliances', icon: '🧊', accent: '#2E4057', children: [
    { name: 'Refrigerators & Freezers', slug: 'refrigeration' },
    { name: 'Laundry & Ironing', slug: 'laundry' },
    { name: 'Air Cooling & Fans', slug: 'air-cooling' },
    { name: 'Cookers & Microwaves', slug: 'cookers' },
  ] },
  { name: 'Beauty & Health', slug: 'beauty-health', icon: '💄', accent: '#513C74', children: [
    { name: 'Skincare', slug: 'skincare' },
    { name: 'Hair, Wigs & Extensions', slug: 'hair-wigs' },
    { name: 'Makeup', slug: 'makeup' },
    { name: 'Fragrances', slug: 'fragrances' },
    { name: 'Wellness & Personal Care', slug: 'wellness' },
  ] },
  { name: 'Groceries', slug: 'groceries', icon: '🛒', accent: '#7A5B1E', children: [
    { name: 'Rice, Grains & Flour', slug: 'grains' },
    { name: 'Beverages & Juices', slug: 'beverages' },
    { name: 'Oils, Spices & Condiments', slug: 'oils-spices' },
    { name: 'Snacks & Confectionery', slug: 'snacks' },
  ] },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors', icon: '⚽', accent: '#04D9FF', children: [
    { name: 'Fitness & Gym', slug: 'fitness' },
    { name: 'Football & Team Sports', slug: 'football' },
    { name: 'Camping & Outdoor', slug: 'camping' },
  ] },
  { name: 'Automobile & Tools', slug: 'auto-tools', icon: '🔧', accent: '#FF7A59', children: [
    { name: 'Car Accessories', slug: 'car-accessories' },
    { name: 'Motorbike & Spare Parts', slug: 'motorbike' },
    { name: 'Power & Hand Tools', slug: 'tools' },
    { name: 'Solar & Generators', slug: 'solar-generators' },
  ] },
  { name: 'Books & Stationery', slug: 'books-stationery', icon: '📚', accent: '#5FD08A', children: [
    { name: 'Books', slug: 'books' },
    { name: 'School Supplies', slug: 'school-supplies' },
    { name: 'Office Supplies', slug: 'office-supplies' },
  ] },
];

const BRANDS = [
  { name: 'Samsung', tagline: 'Do what you can’t' },
  { name: 'Apple', tagline: 'Think different' },
  { name: 'Tecno', tagline: 'Stop at nothing' },
  { name: 'Infinix', tagline: 'The future is now' },
  { name: 'Xiaomi', tagline: 'Innovation for everyone' },
  { name: 'itel', tagline: 'How are you today' },
  { name: 'Nokia', tagline: 'Connecting people' },
  { name: 'Hisense', tagline: 'Life reimagined' },
  { name: 'LG', tagline: 'Life’s good' },
  { name: 'Sony', tagline: 'Make. Believe' },
  { name: 'JBL', tagline: 'Hear the truth' },
  { name: 'Oraimo', tagline: 'Smart life, smart gear' },
  { name: 'Anker', tagline: 'Charge confidently' },
  { name: 'HP', tagline: 'Keep reinventing' },
  { name: 'Dell', tagline: 'The power to do more' },
  { name: 'Lenovo', tagline: 'Smarter technology' },
  { name: 'ASUS', tagline: 'In search of incredible' },
  { name: 'Canon', tagline: 'Delighting you always' },
  { name: 'Nasco', tagline: 'Built for Ghanaian homes' },
  { name: 'Binatone', tagline: 'Kitchen confidence' },
  { name: 'Silver Crest', tagline: 'Value appliances' },
  { name: 'Midea', tagline: 'Make yourself at home' },
  { name: 'Philips', tagline: 'Sense and simplicity' },
  { name: 'Panasonic', tagline: 'Ideas for life' },
  { name: 'Sunu Wear', tagline: 'Accra streetwear' },
  { name: 'Kente Royal', tagline: 'Heritage, woven' },
  { name: 'Adinkra Co.', tagline: 'Symbols of Ghana' },
  { name: 'Ruchelu', tagline: 'Effortless African fashion' },
  { name: 'Shea Radiance', tagline: 'Pure Ghanaian shea' },
  { name: 'Kama Botanicals', tagline: 'Skin, fed naturally' },
  { name: 'Twellium', tagline: 'Just juice' },
  { name: 'FanMilk', tagline: 'Ghana’s favourite' },
  { name: 'Nike', tagline: 'Just do it' },
  { name: 'Adidas', tagline: 'Impossible is nothing' },
  { name: 'Puma', tagline: 'Forever faster' },
  { name: 'Bosch', tagline: 'Invented for life' },
  { name: 'Total Tools', tagline: 'Tough by design' },
  { name: 'Sedco Publishing', tagline: 'Ghanaian stories' },
  { name: 'Biahens Select', tagline: 'Hand-picked by our buyers' },
];

/**
 * Products. `cat` is the child-category slug, `brand` the brand name.
 * price / compare are GHS. `var` adds selectable options with own stock.
 */
const PRODUCTS = [
  // ------------------------------------------------ Phones & Tablets
  { name: 'Samsung Galaxy A55 5G — 8GB RAM / 256GB', cat: 'smartphones', brand: 'Samsung', price: 6299, compare: 7150, stock: 24, weight: 0.42, featured: true, tags: '5g,dual sim,samsung,oled',
    short: 'Super AMOLED 120Hz display, 50MP OIS camera and a 5,000mAh battery that lasts two days of Accra hustle.',
    desc: 'The Galaxy A55 5G brings a flagship feel to the mid-range: a 6.6-inch Super AMOLED panel at 120Hz, a metal frame, IP67 dust and water resistance, and Samsung’s 50MP main camera with optical image stabilisation for sharp low-light shots.\n\nPowered by the Exynos 1480 with 8GB RAM and 256GB storage (expandable to 1TB), it handles multitasking, mobile money apps and gaming without breaking a sweat. Four generations of Android upgrades and five years of security patches keep it current.\n\nIn the box: handset, USB-C cable, SIM ejector, quick-start guide. (Charging adapter sold separately.)',
    var: [{ title: 'Awesome Navy / 256GB', stock: 10 }, { title: 'Awesome Iceblue / 256GB', stock: 8 }, { title: 'Awesome Violet / 256GB', stock: 6 }] },
  { name: 'Apple iPhone 15 — 128GB (Blue)', cat: 'smartphones', brand: 'Apple', price: 13450, compare: 14990, stock: 12, weight: 0.38, featured: true, tags: 'iphone,apple,usb-c,camera',
    short: 'A16 Bionic chip, 48MP main camera and USB-C — the iPhone that finally dropped Lightning.',
    desc: 'iPhone 15 pairs a 6.1-inch Super Retina XDR display with the A16 Bionic chip for effortless performance. The 48MP main camera captures stunning detail, and 2x optical-quality zoom keeps you close to the action.\n\nDynamic Island surfaces alerts and Live Activities, while USB-C means one cable for your Mac, iPad and iPhone. Ceramic Shield front, aerospace-grade aluminium and IP68 water resistance.\n\nBattery: up to 20 hours video playback. Face ID. 5G. Ships with USB-C cable and documentation.' },
  { name: 'Tecno Camon 30 Premier 5G — 12GB / 512GB', cat: 'smartphones', brand: 'Tecno', price: 5199, compare: 5899, stock: 31, weight: 0.44, tags: 'tecno,5g,camera,fast charge',
    short: 'Sony IMX890 sensor, 70W ultra charge and a curved 1.5K AMOLED screen.',
    desc: 'Tecno’s flagship-killer. A 6.77-inch curved 1.5K AMOLED at 120Hz, Dimensity 8200 Ultimate 5G chipset, 12GB RAM and a whopping 512GB of storage.\n\nThe Sony IMX890 50MP sensor with OIS plus a 50MP ultra-wide deliver class-leading photos, while 70W Ultra Charge fills the 5,000mAh battery in under 45 minutes.',
    var: [{ title: 'Basaltic Dark / 512GB', stock: 18 }, { title: 'Palmyra Green / 512GB', stock: 13 }] },
  { name: 'Infinix Note 40 Pro — 8GB / 256GB', cat: 'smartphones', brand: 'Infinix', price: 3299, compare: 3650, stock: 40, weight: 0.4, tags: 'infinix,amoled,magcharge',
    short: '120Hz AMOLED, 108MP camera and All-Round FastCharge 2.0 with magnetic wireless.',
    desc: 'The Note 40 Pro is built around a 6.78-inch 120Hz AMOLED display and MediaTek Helio G99 Ultimate. A 108MP main sensor captures crisp detail, and the 5,000mAh battery supports 70W wired plus 20W magnetic wireless charging.\n\nJBL-tuned dual speakers, in-display fingerprint reader, XOS 14 with a 5-year software promise.' },
  { name: 'Xiaomi Redmi Note 13 — 8GB / 256GB', cat: 'smartphones', brand: 'Xiaomi', price: 2749, compare: 2999, stock: 55, weight: 0.39, tags: 'xiaomi,redmi,budget',
    short: '120Hz AMOLED, 108MP triple camera and 33W fast charging at a serious price.',
    desc: 'Redmi Note 13 delivers a 6.67-inch 120Hz AMOLED with 1800 nits peak brightness, a 108MP main camera and Snapdragon 685 performance.\n\n5,000mAh battery, 33W turbo charging, IP54 splash resistance, dual speakers with Dolby Atmos and a 3.5mm headphone jack.' },
  { name: 'itel A70 — 4GB / 128GB', cat: 'smartphones', brand: 'itel', price: 899, compare: 1099, stock: 88, weight: 0.36, tags: 'itel,budget,big battery',
    short: 'The everyday smartphone: 5,000mAh battery, 6.6-inch display and 128GB storage.',
    desc: 'itel A70 is the value champion — a 6.6-inch HD+ display, 5,000mAh battery, 13MP AI dual rear camera, 8MP front camera with flash and a side-mounted fingerprint reader.\n\n4GB RAM (expandable with virtual RAM) and 128GB storage keeps photos, WhatsApp and MoMo apps comfortable. Android 13 (Go edition).' },
  { name: 'Nokia 106 Dual SIM (2023) Feature Phone', cat: 'feature-phones', brand: 'Nokia', price: 219, compare: 260, stock: 120, weight: 0.12, tags: 'nokia,feature phone,big battery',
    short: 'Weeks of standby, wireless FM radio and a torch — the reliable backup phone.',
    desc: 'The Nokia 106 keeps you connected for up to 19 days on standby. It has a 1.8-inch display, wireless FM radio, a built-in torch, Snake and 2,000 contact slots.\n\nDual SIM, micro-USB charging and a polycarbonate shell that shrugs off drops.' },
  { name: 'Samsung Galaxy Tab A9+ — 8GB / 128GB (Wi-Fi)', cat: 'tablets', brand: 'Samsung', price: 3199, compare: 3499, stock: 18, weight: 0.62, tags: 'tablet,samsung,90hz',
    short: '11-inch 90Hz display, quad speakers and multi-window productivity.',
    desc: 'An 11-inch LCD at 90Hz, Snapdragon 695, 8GB RAM and 128GB expandable storage make the Tab A9+ perfect for streaming, e-learning and light work.\n\nFour speakers with Dolby Atmos, Samsung DeX-free multi-window support and up to 13 hours of video playback.' },
  { name: 'Apple iPad 10.9" (10th Gen) — 64GB Wi-Fi', cat: 'tablets', brand: 'Apple', price: 7899, compare: 8450, stock: 9, weight: 0.7, tags: 'ipad,apple,tablet',
    short: 'A14 Bionic, Liquid Retina display and USB-C for work and play.',
    desc: 'The redesigned iPad features a 10.9-inch Liquid Retina display, A14 Bionic chip, 12MP wide back camera and ultra-wide front camera with Centre Stage.\n\nUSB-C, Touch ID in the top button, all-day battery, and support for Apple Pencil (USB-C) and Magic Keyboard Folio.' },
  { name: 'Oraimo Power Bank 20,000mAh (OPB-P204DN)', cat: 'phone-accessories', brand: 'Oraimo', price: 349, compare: 420, stock: 96, weight: 0.45, tags: 'power bank,oraimo,fast charge',
    short: '20,000mAh with 22.5W fast charge, dual USB out and a digital display.',
    desc: 'Keep two phones topped up for days. 20,000mAh capacity, 22.5W PD/QC fast charging, dual USB-A plus USB-C, and an LED percentage readout.\n\nNine-layer protection against overcharge, overheat and short circuits. 12-month Biahens warranty.' },
  { name: 'Anker Nano 65W GaN Wall Charger (3-Port)', cat: 'phone-accessories', brand: 'Anker', price: 489, compare: 560, stock: 64, weight: 0.2, tags: 'anker,charger,gan,usb-c',
    short: 'One small brick that charges your laptop, phone and buds at full speed.',
    desc: 'GaN II technology packs 65W into a palm-sized charger: 2× USB-C + 1× USB-A with intelligent power sharing.\n\nCharges a MacBook Air to 50% in 30 minutes, an iPhone 15 to 50% in 20 minutes. Foldable pins, ActiveShield 2.0 temperature monitoring.' },
  { name: 'Samsung 25W Super Fast Charging Adapter + Cable', cat: 'phone-accessories', brand: 'Samsung', price: 245, compare: 299, stock: 140, weight: 0.12, tags: 'charger,samsung,usb-c',
    short: 'Genuine Samsung 25W PD adapter with a 1m USB-C to USB-C cable.',
    desc: 'Official Samsung EP-T2510 adapter delivering 25W Super Fast Charging over USB-C Power Delivery 3.0 with PPS.\n\nIncludes a 1-metre 5A USB-C cable. Compatible with Galaxy A and S series, tablets and other PD devices.' },
  { name: 'Refurbished iPhone 12 — 64GB (Grade A)', cat: 'refurbished-phones', brand: 'Apple', price: 4599, compare: 5999, stock: 14, weight: 0.35, tags: 'refurbished,iphone,apple,grade a',
    short: 'Battery health 88%+, cosmetically excellent, 6-month Biahens warranty.',
    desc: 'Grade A refurbished iPhone 12: fully tested, professionally cleaned, screen and body in excellent condition with at most faint micro-scratches.\n\nA14 Bionic, 6.1-inch Super Retina XDR, 12MP dual camera, 5G. Battery health 88% or above. Includes charging cable and a free clear case.\n\nCovered by a 6-month Biahens Enterprise warranty and 7-day return policy.',
    var: [{ title: 'Black / 64GB', stock: 5 }, { title: 'White / 64GB', stock: 4 }, { title: 'Blue / 64GB', stock: 5 }] },
  { name: 'Refurbished Tecno Spark 10 Pro — 8GB / 256GB', cat: 'refurbished-phones', brand: 'Tecno', price: 1499, compare: 2199, stock: 22, weight: 0.4, tags: 'refurbished,tecno,budget',
    short: 'Tested, cleaned and warrantied — big screen and storage for less.',
    desc: 'Grade A refurbished Tecno Spark 10 Pro with a 6.78-inch 90Hz display, 8GB RAM, 256GB storage and 5,000mAh battery.\n\nEvery unit passes our 42-point inspection. Battery health guaranteed at 85%+. 3-month Biahens warranty.' },

  // ------------------------------------------------ Electronics
  { name: 'Samsung 55" Crystal UHD 4K Smart TV (CU7000)', cat: 'tv-video', brand: 'Samsung', price: 6899, compare: 7999, stock: 15, weight: 15.2, featured: true, tags: 'tv,4k,samsung,smart tv',
    short: 'Crystal Processor 4K, HDR10+, Tizen smart apps and a slim bezel-less design.',
    desc: 'A 55-inch 4K UHD panel driven by Samsung’s Crystal Processor 4K, with PurColour and HDR10+ for deeper contrast.\n\nTizen OS gives you Netflix, YouTube, Showmax and Prime Video, plus Multi View and Q-Symphony with compatible soundbars. Three HDMI ports (one eARC), two USB, optical out and Bluetooth audio.' },
  { name: 'Hisense 43" Full HD Android TV (43A4K)', cat: 'tv-video', brand: 'Hisense', price: 3299, compare: 3799, stock: 26, weight: 8.6, tags: 'tv,hisense,android tv',
    short: 'Android TV with Google Assistant, Chromecast built-in and Dolby Audio.',
    desc: 'Full HD 1080p on a 43-inch screen with Android TV, Chromecast built-in and Google Assistant for hands-free control.\n\nDolby Audio, three HDMI ports, two USB, Bluetooth and a slim wall-mountable design.' },
  { name: 'LG 32" HD Smart TV (32LR650B)', cat: 'tv-video', brand: 'LG', price: 2499, compare: 2799, stock: 20, weight: 5.4, tags: 'tv,lg,webos',
    short: 'webOS smart platform, α5 processor and a compact 32-inch HD panel.',
    desc: 'Perfect for bedrooms and shops. webOS 23, α5 AI processor, HDR10/HLG, and Magic Remote compatibility.\n\nTwo HDMI, one USB, Bluetooth surround support and a slim panel that wall-mounts cleanly.' },
  { name: 'JBL Flip 6 Portable Bluetooth Speaker', cat: 'audio-headphones', brand: 'JBL', price: 1349, compare: 1599, stock: 38, weight: 0.55, tags: 'jbl,speaker,bluetooth,waterproof',
    short: 'IP67 waterproof, 12 hours of playtime and legendary JBL bass.',
    desc: 'The Flip 6 uses a race-track woofer, separate tweeter and dual passive radiators for punchy, detailed sound.\n\nIP67 dustproof and waterproof, 12 hours of playtime, PartyBoost pairing and Bluetooth 5.1.' },
  { name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones', cat: 'audio-headphones', brand: 'Sony', price: 4199, compare: 4699, stock: 16, weight: 0.25, tags: 'sony,headphones,anc,bluetooth',
    short: 'Industry-leading noise cancellation, 30-hour battery and crystal-clear calls.',
    desc: 'Eight microphones and two processors cancel more noise than ever, while 30mm drivers keep the sound rich and balanced.\n\nUp to 30 hours of battery, 3-minute quick charge for 3 hours of playback, multipoint Bluetooth, Speak-to-Chat and a folding-free slim case.' },
  { name: 'Oraimo FreePods 4 ANC Wireless Earbuds', cat: 'audio-headphones', brand: 'Oraimo', price: 399, compare: 520, stock: 110, weight: 0.09, tags: 'oraimo,earbuds,anc,budget',
    short: 'Hybrid ANC, 40-hour total playtime and low-latency game mode.',
    desc: 'Hybrid active noise cancellation up to 35dB, 10mm dynamic drivers, and four microphones with AI call noise reduction.\n\nUp to 10 hours per charge and 40 hours with the case, USB-C fast charge, IPX5 water resistance and 60ms game mode.' },
  { name: 'Canon EOS 4000D DSLR + 18-55mm Lens Kit', cat: 'cameras-drones', brand: 'Canon', price: 4899, compare: 5499, stock: 8, weight: 1.2, tags: 'canon,dslr,camera',
    short: '18MP DSLR with Wi-Fi — the easiest way into real photography.',
    desc: 'An 18MP APS-C sensor, DIGIC 4+ processor and 9-point AF make the 4000D a friendly first DSLR.\n\nShoot 1080p video, transfer over Wi-Fi with the Canon Camera Connect app, and learn with the built-in Feature Guide. Kit includes the EF-S 18-55mm III lens, battery, charger and strap.' },
  { name: 'DJI Mini 4K Drone (Fly More Combo)', cat: 'cameras-drones', brand: 'Canon', price: 8499, compare: 9299, stock: 5, weight: 0.9, tags: 'drone,dji,camera,4k',
    short: 'Under 249g, 4K/30fps video, 31-minute flight time and a 2-axis gimbal.',
    desc: 'Weighing less than 249g, the DJI Mini 4K captures 4K/30fps video and 12MP photos on a mechanically stabilised 2-axis gimbal.\n\n31 minutes of flight time, 10km HD video transmission, QuickShots modes and Return-to-Home. Fly More Combo adds two extra batteries, a charging hub and a shoulder bag.' },
  { name: 'Sony PlayStation 5 Slim — 1TB (Disc Edition)', cat: 'gaming', brand: 'Sony', price: 8299, compare: 8999, stock: 7, weight: 4.2, featured: true, tags: 'ps5,playstation,gaming,console',
    short: '1TB SSD, 4K gaming at up to 120Hz, ray tracing and DualSense haptics.',
    desc: 'The PS5 Slim keeps everything players love — ultra-fast SSD, ray tracing, 4K at up to 120fps — in a 30% smaller chassis with 1TB of storage.\n\nIncludes one DualSense wireless controller with haptic feedback and adaptive triggers, HDMI cable and power cord. Disc edition plays PS5 and PS4 game discs.' },
  { name: 'Xbox Series X — 1TB Console Bundle', cat: 'gaming', brand: 'Biahens Select', price: 7999, compare: 8600, stock: 6, weight: 5.1, tags: 'xbox,gaming,console',
    short: '12 teraflops of power, 4K at 120fps and Quick Resume across games.',
    desc: 'The fastest, most powerful Xbox ever: custom Zen 2 + RDNA 2 architecture, 1TB SSD, hardware-accelerated ray tracing and up to 120fps in 4K.\n\nBundle includes the console, one wireless controller, HDMI 2.1 cable and a 14-day Game Pass trial.' },
  { name: 'Apple Watch Series 9 (GPS) 45mm — Midnight', cat: 'smart-wearables', brand: 'Apple', price: 5499, compare: 5999, stock: 17, weight: 0.08, tags: 'apple watch,wearable,health',
    short: 'S9 chip, Double Tap gesture, bright 2000-nit display and full health tracking.',
    desc: 'Series 9 adds the S9 SiP for on-device Siri, Double Tap for one-handed control and a display that hits 2000 nits in Accra sunshine.\n\nECG, blood oxygen, heart rate, temperature sensing, sleep stages, crash detection and 18-hour battery (36 in Low Power Mode). Includes a Midnight Sport Band.' },
  { name: 'Oraimo Watch 4 Pro Smartwatch — 2.01" AMOLED', cat: 'smart-wearables', brand: 'Oraimo', price: 549, compare: 699, stock: 74, weight: 0.1, tags: 'smartwatch,oraimo,budget,amoled',
    short: 'Bluetooth calling, 100+ sport modes and a 10-day battery.',
    desc: 'A huge 2.01-inch AMOLED display, Bluetooth calling, AI voice assistant and over 100 sport modes with SpO2 and heart-rate tracking.\n\nIP68 water resistance and up to 10 days of battery life. Works with Android 6.0+ and iOS 12+.' },

  // ------------------------------------------------ Computing
  { name: 'HP Pavilion 15 Laptop — Intel Core i7 / 16GB / 512GB SSD', cat: 'laptops', brand: 'HP', price: 11499, compare: 12800, stock: 11, weight: 1.75, featured: true, tags: 'hp,laptop,core i7,16gb',
    short: '13th Gen Core i7, 16GB RAM, 512GB NVMe SSD and a 15.6" FHD IPS display.',
    desc: 'A dependable all-rounder: Intel Core i7-1355U, 16GB DDR4, 512GB PCIe NVMe SSD and Intel Iris Xe graphics.\n\n15.6-inch Full HD IPS anti-glare display, backlit keyboard, HP Fast Charge (50% in 45 minutes), Wi-Fi 6, HDMI 2.1, USB-C and a 1080p privacy camera with temporal noise reduction.\n\nWindows 11 Home pre-installed. 1-year Biahens warranty.' },
  { name: 'Apple MacBook Air 13" M3 — 8GB / 256GB (Midnight)', cat: 'laptops', brand: 'Apple', price: 17999, compare: 19499, stock: 6, weight: 1.24, tags: 'macbook,apple,m3,laptop',
    short: 'M3 chip, 18-hour battery, Liquid Retina display and a fanless silent design.',
    desc: 'The M3 MacBook Air is 1.24kg of silent, all-day performance: 8-core CPU, 10-core GPU, 8GB unified memory and 256GB SSD.\n\n13.6-inch Liquid Retina display at 500 nits, 1080p FaceTime HD camera, MagSafe 3, two Thunderbolt ports and support for two external displays with the lid closed.' },
  { name: 'Lenovo IdeaPad Slim 3 — Ryzen 5 / 8GB / 512GB', cat: 'laptops', brand: 'Lenovo', price: 6799, compare: 7499, stock: 19, weight: 1.63, tags: 'lenovo,laptop,ryzen 5,student',
    short: 'AMD Ryzen 5 7520U, 15.6" FHD display and a full-year warranty.',
    desc: 'Great value for students and small offices: AMD Ryzen 5 7520U, 8GB LPDDR5, 512GB SSD and Radeon 610M graphics.\n\n15.6-inch Full HD anti-glare display, Dolby Audio, 720p webcam with privacy shutter, USB-C, HDMI 1.4b and Windows 11 Home.' },
  { name: 'Dell OptiPlex 3080 Desktop (Refurbished) — i5 / 8GB / 256GB', cat: 'desktops', brand: 'Dell', price: 3899, compare: 4699, stock: 13, weight: 5.6, tags: 'dell,desktop,refurbished,office',
    short: 'Tested business desktop — perfect for shops, schools and POS setups.',
    desc: 'Refurbished Dell OptiPlex 3080 SFF: Intel Core i5-10500, 8GB DDR4, 256GB NVMe SSD, Intel UHD 630 graphics.\n\nPorts: 4× USB 3.2, 4× USB 2.0, HDMI, DisplayPort, RJ-45 gigabit Ethernet. Windows 11 Pro. Every unit passes a 30-point hardware check and ships with a keyboard and mouse. 6-month warranty.' },
  { name: 'ASUS 27" VA279QGR Full HD IPS Monitor — 165Hz', cat: 'monitors', brand: 'ASUS', price: 2199, compare: 2499, stock: 22, weight: 4.8, tags: 'monitor,asus,gaming,165hz',
    short: '27-inch IPS, 165Hz, 1ms and AMD FreeSync Premium.',
    desc: 'A 27-inch Full HD IPS panel with 178° viewing angles, 165Hz refresh and 1ms (MPRT) response — smooth for both work and gaming.\n\nAMD FreeSync Premium, ASUS Eye Care low-blue-light and flicker-free tech, HDMI + DisplayPort inputs and a tilt-adjustable stand (VESA 100 mountable).' },
  { name: 'HP LaserJet Pro MFP M28w Printer (Print/Scan/Copy)', cat: 'printers', brand: 'HP', price: 2450, compare: 2750, stock: 12, weight: 5.4, tags: 'printer,hp,laserjet,wifi',
    short: 'Compact mono laser MFP with Wi-Fi, mobile printing and low running costs.',
    desc: 'One of the smallest mono laser MFPs HP makes: print up to 18ppm, scan and copy in a footprint that fits any desk.\n\nWi-Fi and Wi-Fi Direct, Apple AirPrint, Mopria and HP Smart app support. Uses the reliable HP 44A toner cartridge.' },
  { name: 'Seagate Expansion 2TB Portable External HDD', cat: 'storage-networking', brand: 'Biahens Select', price: 799, compare: 950, stock: 45, weight: 0.23, tags: 'storage,hdd,backup,2tb',
    short: 'Plug-and-play 2TB backup drive with USB 3.0.',
    desc: '2TB of portable storage in a slim enclosure. USB 3.0 (backwards compatible with USB 2.0), drag-and-drop backup and Windows/macOS support.\n\nIncludes a 45cm USB 3.0 cable and Seagate Toolkit backup software.' },
  { name: 'TP-Link Archer C64 AC1200 Dual-Band Wi-Fi Router', cat: 'storage-networking', brand: 'Biahens Select', price: 449, compare: 549, stock: 58, weight: 0.45, tags: 'router,wifi,tp-link,networking',
    short: 'Dual-band AC1200 Wi-Fi with MU-MIMO, 4 antennas and guest network.',
    desc: 'AC1200 speeds — 867Mbps on 5GHz and 300Mbps on 2.4GHz — with four high-gain external antennas and MU-MIMO.\n\nEasy setup via the Tether app, guest network, parental controls, WPA3 support and one gigabit WAN plus four LAN ports.' },
  { name: 'Logitech M185 Wireless Mouse + K120 Keyboard Combo', cat: 'laptop-accessories', brand: 'Biahens Select', price: 289, compare: 350, stock: 82, weight: 0.6, tags: 'mouse,keyboard,logitech,office',
    short: 'Reliable nano-receiver wireless mouse with a spill-resistant USB keyboard.',
    desc: 'The M185 mouse connects with a tiny nano receiver and runs up to 12 months on one AA battery. The K120 keyboard has a spill-resistant design, low-profile keys and bold printed characters.\n\nPlug-and-play on Windows, macOS and ChromeOS.' },
  { name: 'Generic Aluminium Laptop Stand — Foldable & Adjustable', cat: 'laptop-accessories', brand: 'Biahens Select', price: 189, compare: 249, stock: 130, weight: 0.9, tags: 'laptop stand,ergonomic,accessory',
    short: 'Ergonomic aluminium riser that fits 10– 17-inch laptops.',
    desc: 'Raise your screen to eye level and keep your laptop cool. CNC-machined aluminium with silicone pads, six adjustable angles, foldable for travel and open ventilation for better thermals.\n\nSupports up to 8kg and fits laptops and tablets from 10 to 17 inches.' },

  // ------------------------------------------------ Fashion
  { name: "Men's Classic Slim-Fit Oxford Shirt — Cotton", cat: 'mens-clothing', brand: 'Sunu Wear', price: 189, compare: 249, stock: 74, weight: 0.3, tags: 'shirt,men,cotton,office',
    short: 'Breathable 100% cotton Oxford with a slim fit that works at the office or out.',
    desc: 'Cut from 100% long-staple cotton Oxford cloth, pre-washed for softness and minimal shrinkage. Slim fit, button-down collar, single chest pocket and durable pearl-effect buttons.\n\nMachine washable at 30°C. Available in four colours and five sizes.',
    var: [{ title: 'White / M', stock: 14 }, { title: 'White / L', stock: 16 }, { title: 'Sky Blue / M', stock: 12 }, { title: 'Sky Blue / L', stock: 14 }, { title: 'Navy / L', stock: 10 }, { title: 'Navy / XL', stock: 8 }] },
  { name: "Men's Stretch Chino Trousers — Slim Tapered", cat: 'mens-clothing', brand: 'Sunu Wear', price: 219, compare: 289, stock: 56, weight: 0.45, tags: 'trousers,chino,men,smart casual',
    short: 'Cotton-blend twill with 2% elastane for all-day movement.',
    desc: 'A modern slim-tapered chino in 98% cotton / 2% elastane twill. Zip fly with button closure, two front slant pockets, two welt back pockets and a comfortable mid-rise waist.\n\nHolds its shape through a full Accra workday. Machine wash cold, hang dry.' },
  { name: "Women's Ankara Print Midi Dress", cat: 'womens-clothing', brand: 'Ruchelu', price: 349, compare: 449, stock: 41, weight: 0.35, featured: true, tags: 'ankara,dress,women,african print',
    short: 'Vibrant wax-print midi with a cinched waist and side pockets.',
    desc: 'Made from premium 100% cotton Ankara wax print with a lined bodice, concealed back zip, removable waist tie and hidden side pockets.\n\nMidi length sits just below the knee. Each piece is cut and sewn in Accra, so pattern placement varies slightly — that is the point.\n\nCare: hand wash cold separately for the first wash, then machine wash gentle.',
    var: [{ title: 'Indigo Pattern / S', stock: 8 }, { title: 'Indigo Pattern / M', stock: 12 }, { title: 'Indigo Pattern / L', stock: 10 }, { title: 'Sunset Pattern / M', stock: 6 }, { title: 'Sunset Pattern / L', stock: 5 }] },
  { name: "Women's Two-Piece Lounge Set — Ribbed Knit", cat: 'womens-clothing', brand: 'Ruchelu', price: 259, compare: 320, stock: 63, weight: 0.5, tags: 'loungewear,matching set,women',
    short: 'Soft ribbed knit co-ord: relaxed crop top with high-waist wide-leg trousers.',
    desc: 'A buttery-soft ribbed knit set you will actually live in. Relaxed cropped top with short sleeves and a high-waisted wide-leg trouser with an elasticated back waist.\n\n65% viscose / 30% nylon / 5% elastane. Machine wash cold, lay flat to dry.' },
  { name: 'Handwoven Kente Stole — Ashanti Traditional', cat: 'traditional-wear', brand: 'Kente Royal', price: 899, compare: 1150, stock: 18, weight: 0.4, tags: 'kente,traditional,graduation,ghana',
    short: 'Authentic handwoven Asante kente in ceremonial gold, green and red.',
    desc: 'Each stole is handwoven on a traditional loom in Bonwire, Ashanti Region, from 100% cotton and rayon-silk thread.\n\nApproximately 180cm × 25cm with hand-knotted fringe. Suitable for graduations, weddings, naming ceremonies and corporate gifting. Colours carry meaning: gold for status, green for renewal, red for sacrifice, black for maturity.\n\nBecause every piece is woven by hand, no two are identical.' },
  { name: 'Adinkra Symbol Cotton T-Shirt (Unisex)', cat: 'traditional-wear', brand: 'Adinkra Co.', price: 129, compare: 165, stock: 96, weight: 0.22, tags: 't-shirt,adinkra,unisex,ghana',
    short: 'Heavyweight cotton tee with a screen-printed Gye Nyame motif.',
    desc: '200gsm combed cotton, unisex regular fit, ribbed collar and double-needle stitching. The Gye Nyame motif ("except for God") is screen-printed with water-based ink that stays soft through washes.\n\nMade in Ghana. Sizes XS–XXL.' },
  { name: 'Kids Denim Dungarees — Ages 2 to 8', cat: 'kids-baby', brand: 'Ruchelu', price: 179, compare: 229, stock: 44, weight: 0.3, tags: 'kids,denim,dungarees',
    short: 'Adjustable-strap denim dungarees with reinforced knees.',
    desc: 'Soft-washed cotton denim with adjustable button straps, a front bib pocket, reinforced knees and side button openings for easy changes.\n\nAges 2–8. Machine wash warm, tumble dry low.' },
  { name: 'Baby Organic Cotton Bodysuit 5-Pack', cat: 'kids-baby', brand: 'Ruchelu', price: 245, compare: 310, stock: 52, weight: 0.4, tags: 'baby,organic,cotton,bodysuit',
    short: 'GOTS-certified organic cotton bodysuits with envelope shoulders.',
    desc: 'Five short-sleeve bodysuits in GOTS-certified organic cotton. Envelope shoulders make dressing easier, nickel-free snaps are gentle on skin, and flatlock seams prevent chafing.\n\nSizes 0–3m to 18–24m. Machine wash hot, tumble dry.' },
  { name: 'Casio Vintage A168WA Stainless Steel Digital Watch', cat: 'watches-jewellery', brand: 'Biahens Select', price: 495, compare: 620, stock: 33, weight: 0.09, tags: 'casio,watch,digital,vintage',
    short: 'The timeless retro digital — stopwatch, alarm and 7-year battery.',
    desc: 'A design icon since the 1980s. Stainless steel band with adjustable clasp, EL backlight, 1/100-second stopwatch, daily alarm, hourly time signal and automatic calendar.\n\nWater resistant to everyday splashes, approximately 7-year battery life, 33mm case.' },
  { name: 'Gold-Plated Ankh Pendant Necklace — 18"', cat: 'watches-jewellery', brand: 'Adinkra Co.', price: 320, compare: 420, stock: 27, weight: 0.05, tags: 'necklace,jewellery,gold,ankh',
    short: '18k gold-plated brass pendant on a hypoallergenic chain.',
    desc: 'The ankh — the ancient symbol of life — cast in brass and plated in 18k gold, hanging from an 18-inch stainless steel chain with a 2-inch extender.\n\nTarnish-resistant and nickel-free. Arrives in a Biahens gift box.' },

  // ------------------------------------------------ Shoes & Bags
  { name: 'Nike Air Zoom Pegasus 41 Running Shoes', cat: 'sneakers', brand: 'Nike', price: 1549, compare: 1849, stock: 29, weight: 0.7, featured: true, tags: 'nike,sneakers,running,shoes',
    short: 'Responsive ReactX foam and Zoom Air units for daily miles.',
    desc: 'The workhorse returns with ReactX midsole foam for 13% more energy return, plus Zoom Air units in the forefoot and heel.\n\nEngineered mesh upper breathes in hot weather, a wider toe box fits more foot shapes, and the waffle outsole grips road and light trail.\n\nSizes UK 5–12.',
    var: [{ title: 'Black/White / UK 7', stock: 5 }, { title: 'Black/White / UK 8', stock: 7 }, { title: 'Black/White / UK 9', stock: 6 }, { title: 'Black/White / UK 10', stock: 5 }, { title: 'White/Blue / UK 8', stock: 3 }, { title: 'White/Blue / UK 9', stock: 3 }] },
  { name: 'Adidas Samba OG Classic Trainers', cat: 'sneakers', brand: 'Adidas', price: 1299, compare: 1499, stock: 24, weight: 0.75, tags: 'adidas,samba,sneakers,classic',
    short: 'The terrace classic: full-grain leather upper with a gum rubber outsole.',
    desc: 'Born on the indoor football pitch in 1950, the Samba OG keeps the original recipe — soft full-grain leather, suede T-toe overlay, gum rubber outsole and the classic three-stripes.\n\nLeather lining, die-cut EVA midsole. Unisex sizing UK 4–12.' },
  { name: 'Puma Smash v2 Leather Sneakers', cat: 'sneakers', brand: 'Puma', price: 749, compare: 899, stock: 37, weight: 0.8, tags: 'puma,sneakers,leather,casual',
    short: 'Clean low-profile leather sneakers with a cushioned SoftFoam+ footbed.',
    desc: 'A tennis-inspired silhouette in smooth leather with the signature Puma Formstrip. SoftFoam+ sockliner provides step-in comfort, and the rubber cupsole gives everyday durability.\n\nUnisex UK 4–12.' },
  { name: "Men's Leather Oxford Formal Shoes — Hand-Finished", cat: 'formal-shoes', brand: 'Sunu Wear', price: 649, compare: 820, stock: 26, weight: 1.1, tags: 'formal shoes,leather,oxford,men',
    short: 'Full-grain leather Oxfords with a Goodyear-style stitched sole.',
    desc: 'Hand-finished full-grain leather uppers, leather lining, padded footbed and a stitched rubber-blend sole for grip on tiled office floors.\n\nClosed-lace Oxford construction. Sizes UK 6–12. Includes a dust bag and shoe horn.' },
  { name: "Women's Block-Heel Ankle Strap Sandals", cat: 'sandals-slippers', brand: 'Ruchelu', price: 379, compare: 460, stock: 43, weight: 0.6, tags: 'sandals,women,heels',
    short: '7cm block heel with a cushioned footbed — comfortable enough for a whole wedding.',
    desc: 'Faux-suede upper with an adjustable ankle buckle, 7cm block heel and a cushioned latex footbed lined in breathable PU.\n\nNon-slip textured outsole. Sizes EU 36–42.' },
  { name: 'Unisex EVA Slide Sandals — Anti-Skid', cat: 'sandals-slippers', brand: 'Biahens Select', price: 89, compare: 130, stock: 160, weight: 0.3, tags: 'slides,sandals,unisex,budget',
    short: 'Lightweight moulded EVA slides with a massage-textured footbed.',
    desc: 'One-piece moulded EVA that is waterproof, quick-drying and easy to wipe clean. The footbed has a gentle massage texture and the outsole is anti-skid.\n\nSizes EU 36–46. Ideal for home, beach and the pool.' },
  { name: 'Leather Structured Tote Handbag — 3-Compartment', cat: 'handbags', brand: 'Ruchelu', price: 529, compare: 690, stock: 31, weight: 0.9, tags: 'handbag,tote,leather,women',
    short: 'Fits a 14-inch laptop with room for everything else.',
    desc: 'Pebbled PU leather with gold-tone hardware, three main compartments, interior zip and slip pockets, and a detachable adjustable shoulder strap.\n\n32 × 27 × 13 cm — comfortably holds a 14-inch laptop, a water bottle and a make-up pouch. Dust bag included.' },
  { name: 'Anti-Theft Travel Backpack with USB Port — 25L', cat: 'backpacks-luggage', brand: 'Biahens Select', price: 429, compare: 549, stock: 48, weight: 0.85, tags: 'backpack,travel,usb,anti-theft',
    short: 'Water-repellent 25L daypack with hidden zips, laptop sleeve and USB charging port.',
    desc: '25 litres of organised carrying: padded 15.6-inch laptop sleeve, hidden back pocket for passports, RFID-blocking card slot, and a built-in USB-A port that connects to your own power bank.\n\nWater-repellent 900D polyester, lockable main zips, breathable mesh back panel and a trolley pass-through strap.' },
  { name: 'Hard-Shell Cabin Luggage 20" — 360° Spinner', cat: 'backpacks-luggage', brand: 'Biahens Select', price: 899, compare: 1199, stock: 21, weight: 3.1, tags: 'luggage,travel,cabin,suitcase',
    short: 'Airline-cabin size with a TSA lock and four silent spinner wheels.',
    desc: 'Scratch-resistant ABS+PC shell, 20-inch cabin dimensions (55 × 35 × 22cm), fully lined interior with compression straps and a zip divider.\n\nFour 360° silent spinner wheels, telescopic aluminium handle, integrated 3-digit TSA combination lock and reinforced corner guards.' },

  // ------------------------------------------------ Home & Kitchen
  { name: 'Nasco 12-Piece Non-Stick Cookware Set', cat: 'cookware', brand: 'Nasco', price: 749, compare: 949, stock: 33, weight: 6.2, tags: 'cookware,non stick,pots,nasco',
    short: 'Induction-ready non-stick set with tempered glass lids.',
    desc: 'Twelve pieces to equip a whole kitchen: 20cm, 24cm and 28cm frypans; 3L and 5L saucepans with lids; and a 7L stockpot with lid.\n\nForged aluminium body with a triple-layer non-stick coating, soft-touch bakelite handles, tempered glass lids with steam vents and induction-compatible bases.' },
  { name: 'Binatone 1.5L Blender with Mill (BLG-402)', cat: 'kitchen-appliances', brand: 'Binatone', price: 499, compare: 620, stock: 47, weight: 2.4, tags: 'blender,binatone,kitchen',
    short: '400W blender with a stainless mill for dry pepper and spices.',
    desc: 'A 400W motor with two speeds plus pulse, a 1.5-litre unbreakable jar and a dedicated mill attachment for grinding dried pepper, cloves and dawadawa.\n\nStainless steel blades, safety interlock, non-slip feet and overload protection.' },
  { name: 'Silver Crest 2.8L Air Fryer — Digital', cat: 'kitchen-appliances', brand: 'Silver Crest', price: 699, compare: 899, stock: 36, weight: 4.1, tags: 'air fryer,silver crest,kitchen,healthy',
    short: 'Eight presets, rapid air circulation and 85% less oil.',
    desc: 'A 2.8-litre non-stick basket, 1400W rapid-air circulation and eight one-touch presets (fries, chicken, fish, shrimp, cake and more).\n\nDigital touch panel with temperature from 80–200°C, 60-minute timer with auto shut-off, dishwasher-safe basket and a cool-touch handle.' },
  { name: 'Philips Daily Collection Electric Kettle 1.7L', cat: 'kitchen-appliances', brand: 'Philips', price: 349, compare: 429, stock: 54, weight: 1.1, tags: 'kettle,philips,kitchen',
    short: 'Boils a cup in under a minute with automatic shut-off.',
    desc: '1.7-litre food-grade PP body, 1800–2150W concealed stainless element, one-touch lid, 360° cordless base with cord storage and a multi-safety system against dry boiling.' },
  { name: 'Solid Mahogany 6-Seater Dining Set', cat: 'furniture', brand: 'Biahens Select', price: 8999, compare: 10999, stock: 4, weight: 78, tags: 'dining table,furniture,mahogany',
    short: 'Handmade in Ghana from solid mahogany — table plus six upholstered chairs.',
    desc: 'A 180 × 90cm solid mahogany dining table with six matching chairs upholstered in easy-clean fabric.\n\nBuilt by our partner workshop in Kumasi from kiln-dried Ghanaian mahogany, finished with a hardwax oil that resists heat and spills.\n\nDelivery includes assembly in Greater Accra, Ashanti and Central regions. Allow 5–10 working days for finishing.' },
  { name: '3-Seater Fabric Sofa with Reversible Chaise', cat: 'furniture', brand: 'Biahens Select', price: 6499, compare: 7999, stock: 6, weight: 55, tags: 'sofa,furniture,living room',
    short: 'Reversible chaise, high-density foam and stain-resistant fabric.',
    desc: 'A modern 3-seater with a chaise that fits either side of the room. Kiln-dried hardwood frame, high-density foam cushions, sinuous spring support and stain-resistant polyester upholstery.\n\n218 × 145 × 82cm. Delivered partially assembled — legs and chaise attach in about 15 minutes.' },
  { name: 'Egyptian Cotton 4-Piece Bedding Set — Queen', cat: 'bedding-bath', brand: 'Biahens Select', price: 599, compare: 799, stock: 42, weight: 2.2, tags: 'bedding,sheets,cotton,queen',
    short: '300-thread-count cotton: duvet cover, flat sheet and two pillowcases.',
    desc: '300-thread-count 100% cotton in a sateen weave that stays cool through the night. Queen set fits a 230 × 220cm duvet.\n\nIncludes duvet cover with button closure, flat sheet and two pillowcases. Machine wash warm, tumble dry low, warm iron if you like.' },
  { name: 'Adinkra Motif Ceramic Vase — 30cm', cat: 'home-decor', brand: 'Adinkra Co.', price: 289, compare: 360, stock: 23, weight: 1.6, tags: 'vase,decor,ceramic,adinkra',
    short: 'Hand-glazed ceramic vase stamped with traditional adinkra symbols.',
    desc: 'Thrown and glazed by artisans in Ahwiaa, this 30cm vase carries a band of hand-stamped adinkra symbols.\n\nWatertight interior for fresh stems, felt-padded base. Each piece varies slightly in tone.' },

  // ------------------------------------------------ Appliances
  { name: 'Midea 320L Double Door Refrigerator (No Frost)', cat: 'refrigeration', brand: 'Midea', price: 5299, compare: 6199, stock: 13, weight: 58, featured: true, tags: 'fridge,midea,no frost,refrigerator',
    short: 'No-frost double door with a 320L capacity and inverter compressor.',
    desc: '320 litres total — 234L fridge, 86L freezer — with Multi-Air Flow no-frost cooling that keeps temperature even on every shelf.\n\nInverter compressor cuts energy use and noise, tempered glass shelves hold up to 20kg, and there is a dedicated vegetable crisper with humidity control.\n\nHandles voltage fluctuation from 160–260V. 5-year compressor warranty.' },
  { name: 'Nasco 9kg Top-Load Automatic Washing Machine', cat: 'laundry', brand: 'Nasco', price: 4199, compare: 4899, stock: 11, weight: 42, tags: 'washing machine,nasco,laundry',
    short: '9kg capacity with 8 wash programmes and a built-in heater.',
    desc: 'A 9kg top-loader with 8 programmes, quick 15-minute wash, soak, spin-only and an in-built heater for hygienic cotton cycles.\n\nDigital display with delay start, child lock, rust-proof body and a powerful 700rpm spin. 2-year Biahens warranty.' },
  { name: 'Midea 1.5HP Split Air Conditioner (Inverter)', cat: 'air-cooling', brand: 'Midea', price: 5899, compare: 6899, stock: 16, weight: 38, tags: 'air conditioner,midea,inverter,cooling',
    short: 'Inverter cooling for rooms up to 20m² with low-voltage start-up.',
    desc: '1.5HP inverter split AC with R32 refrigerant, cooling capacity 12,000 BTU — ideal for bedrooms and small offices up to 20m².\n\nFeatures: turbo cool, sleep curve, self-clean, 24-hour timer, anti-corrosion gold-fin condenser and stable operation from 150V.\n\nPrice includes standard installation within Greater Accra (up to 3m of piping).' },
  { name: 'Binatone 20L Microwave Oven with Grill', cat: 'cookers', brand: 'Binatone', price: 1199, compare: 1450, stock: 25, weight: 12.5, tags: 'microwave,binatone,grill,kitchen',
    short: '20 litres, 700W microwave plus a 1000W grill and 5 power levels.',
    desc: 'A compact 20L cavity with 700W microwave output, a 1000W quartz grill, five power levels, a 35-minute timer, defrost by weight or time and a child safety lock.' },
  { name: 'Nasco 4-Burner Gas Cooker with Oven & Grill', cat: 'cookers', brand: 'Nasco', price: 3899, compare: 4499, stock: 9, weight: 45, tags: 'gas cooker,nasco,oven,kitchen',
    short: 'Four gas burners, a 55L gas oven, grill and flame-failure protection.',
    desc: 'A 60cm freestanding cooker with four enamel-coated gas burners, a 55-litre gas oven, electric grill and rotisserie spit.\n\nFlame-failure safety devices cut gas if a burner goes out, and the glass lid protects the hob when not in use. Adjustable feet for uneven floors.' },

  // ------------------------------------------------ Beauty & Health
  { name: 'Shea Radiance Whipped Body Butter — 250ml', cat: 'skincare', brand: 'Shea Radiance', price: 129, compare: 165, stock: 88, weight: 0.28, tags: 'shea butter,skincare,body butter,natural',
    short: 'Unrefined Northern Ghana shea whipped with baobab and vitamin E.',
    desc: 'Hand-whipped from unrefined shea butter sourced in Bolgatanga, blended with baobab oil, cold-pressed coconut oil and vitamin E.\n\nNo parabens, no mineral oil, no synthetic fragrance. 250ml jar. Suitable for very dry skin, eczema-prone skin and pregnancy.' },
  { name: 'Kama Botanicals Vitamin C Brightening Serum — 30ml', cat: 'skincare', brand: 'Kama Botanicals', price: 245, compare: 310, stock: 61, weight: 0.09, tags: 'serum,vitamin c,skincare,brightening',
    short: '15% vitamin C with ferulic acid and hyaluronic acid.',
    desc: 'A lightweight serum combining 15% L-ascorbic acid, ferulic acid, vitamin E and hyaluronic acid to fade dark spots and even tone.\n\nFragrance-free, alcohol-free, dermatologically tested. 30ml amber glass bottle with dropper. Use in the morning under SPF.' },
  { name: 'Human Hair Lace Front Wig — Body Wave 20"', cat: 'hair-wigs', brand: 'Biahens Select', price: 1899, compare: 2499, stock: 14, weight: 0.35, tags: 'wig,human hair,lace front,body wave',
    short: '100% human hair, 13×4 HD lace, pre-plucked hairline.',
    desc: 'Grade 10A Brazilian human hair in a body wave texture. 20 inches, 180% density, 13×4 HD transparent lace front with a pre-plucked hairline and bleached knots.\n\nCan be straightened, curled and coloured. Includes a free wig cap and lashes. Sizes 22" and 26" available on request.',
    var: [{ title: '20" / 180% density', stock: 8 }, { title: '22" / 180% density', stock: 4 }, { title: '26" / 200% density', stock: 2 }] },
  { name: 'Matte Liquid Lipstick Set — 6 Shades', cat: 'makeup', brand: 'Kama Botanicals', price: 199, compare: 269, stock: 72, weight: 0.12, tags: 'lipstick,makeup,matte,set',
    short: 'Six transfer-resistant matte shades made for deep and medium skin tones.',
    desc: 'Six long-wear liquid lipsticks in shades developed for rich skin tones: Accra Sunset, Harmattan, Cocoa, Kola, Volte and Gold Coast.\n\nNon-drying formula with vitamin E and shea butter, precision doe-foot applicator, 8–10 hours of wear. Cruelty-free and paraben-free.' },
  { name: 'Eau de Parfum — Oud & Amber 100ml', cat: 'fragrances', brand: 'Biahens Select', price: 459, compare: 599, stock: 34, weight: 0.42, tags: 'perfume,oud,fragrance,unisex',
    short: 'Warm oud, amber and bergamot with 8+ hours of projection.',
    desc: 'A unisex eau de parfum at 20% concentration. Top notes of bergamot and saffron, a heart of oud and rose, and a base of amber, sandalwood and musk.\n\n100ml glass spray bottle in a presentation box. Longevity 8–10 hours in Ghana’s climate.' },
  { name: 'Digital Blood Pressure Monitor — Upper Arm', cat: 'wellness', brand: 'Biahens Select', price: 389, compare: 499, stock: 40, weight: 0.55, tags: 'blood pressure,health,monitor,home',
    short: 'Clinically validated cuff monitor with irregular heartbeat detection.',
    desc: 'Upper-arm digital monitor with a 22–42cm cuff, one-touch operation, dual-user memory for 2×120 readings, irregular heartbeat detection and an average of the last three measurements.\n\nLarge backlit LCD, runs on 4× AA batteries (included) or the optional USB adapter. CE marked and clinically validated.' },

  // ------------------------------------------------ Groceries
  { name: 'Premium Jasmine Rice — 25kg Bag', cat: 'grains', brand: 'Biahens Select', price: 449, compare: 529, stock: 66, weight: 25, tags: 'rice,jasmine,grocery,25kg',
    short: 'Long-grain fragrant jasmine rice in a wholesale 25kg bag.',
    desc: 'Grade A long-grain jasmine rice — fluffy, lightly fragrant and low in broken grains (under 5%).\n\n25kg woven bag. Best before 18 months from packing. Store cool and dry. Free delivery in Greater Accra on orders above GH₵1,500.' },
  { name: 'Honeywell Wheat Flour — 2kg (Pack of 4)', case: true, cat: 'grains', brand: 'Biahens Select', price: 189, compare: 232, stock: 84, weight: 8, tags: 'flour,baking,grocery',
    short: 'All-purpose refined wheat flour — four 2kg packs.',
    desc: 'Four 2kg bags of all-purpose refined wheat flour, ideal for bread, pastries, chin chin and meat pies.\n\nFortified with iron, zinc and vitamins A and B. Keep sealed in a dry place.' },
  { name: 'Twellium Just Juice — 1L Mango (Pack of 12)', cat: 'beverages', brand: 'Twellium', price: 219, compare: 264, stock: 57, weight: 12.5, tags: 'juice,mango,twellium,grocery',
    short: 'Twelve 1-litre cartons of Ghana’s favourite mango juice.',
    desc: 'Made from Ghanaian mangoes with no added preservatives or artificial colour. Each 1L Tetra Pak carton contains 100% juice from concentrate.\n\nCase of 12. Serve chilled. Best before 12 months from production.' },
  { name: 'Golden Penny Spaghetti — 500g (Pack of 20)', cat: 'grains', brand: 'Biahens Select', price: 329, compare: 400, stock: 49, weight: 10, tags: 'pasta,spaghetti,wholesale,grocery',
    short: 'A full carton of 500g spaghetti — 20 packs.',
    desc: 'Twenty 500g packs of durum wheat spaghetti. Cooks al dente in 8–10 minutes.\n\nWhole-carton pricing for households, restaurants and chop bars. Store in a cool, dry place.' },
  { name: 'Gino Tomato Paste — 400g Tin (Pack of 12)', cat: 'oils-spices', brand: 'Biahens Select', price: 279, compare: 336, stock: 71, weight: 5.2, tags: 'tomato paste,gino,grocery,cooking',
    short: 'Twelve 400g tins of rich double-concentrate tomato paste.',
    desc: 'Double-concentrate tomato paste (28–30% brix) made from vine-ripened tomatoes. Essential for jollof, light soup and stew.\n\nCase of twelve 400g tins. No artificial colours. Refrigerate after opening and use within 5 days.' },
  { name: 'Devonshire Palm Oil — 5L', cat: 'oils-spices', brand: 'Biahens Select', price: 259, compare: 305, stock: 38, weight: 4.8, tags: 'palm oil,cooking oil,grocery',
    short: 'Pure red palm oil, cold-pressed and unrefined.',
    desc: 'Cold-pressed red palm oil from the Western Region — rich colour and authentic flavour for palm nut soup, waakye and kontomire.\n\n5-litre food-grade container. No additives, no preservatives.' },
  { name: 'FanMilk Family Snack Box — Assorted 24 Pieces', cat: 'snacks', brand: 'FanMilk', price: 149, compare: 185, stock: 44, weight: 1.4, tags: 'snacks,fanmilk,frozen,grocery',
    short: 'Assorted frozen treats delivered in insulated packaging.',
    desc: 'Twenty-four assorted FanMilk favourites — FanIce, FanYogo and FanTop — packed in an insulated box with ice packs.\n\nGreater Accra delivery only, dispatched same day for orders placed before 1pm. Freeze immediately on arrival.' },

  // ------------------------------------------------ Sports & Outdoors
  { name: 'Adjustable Dumbbell Set — 2 × 20kg with Connector', cat: 'fitness', brand: 'Biahens Select', price: 1299, compare: 1599, stock: 19, weight: 41, tags: 'dumbbell,gym,fitness,weights',
    short: 'Converts to a 40kg barbell — cast iron with a non-slip grip.',
    desc: 'Two 20kg adjustable dumbbells with cast-iron plates, chrome knurled handles, star collars and a connecting bar that turns them into a 40kg barbell.\n\nIncludes a moulded carry case. Perfect for a home gym.' },
  { name: '6mm Non-Slip TPE Yoga Mat with Carry Strap', cat: 'fitness', brand: 'Biahens Select', price: 229, compare: 299, stock: 63, weight: 1.1, tags: 'yoga mat,fitness,yoga,pilates',
    short: '6mm cushioning, double-sided texture and a free carry strap.',
    desc: 'Made from TPE — free of latex, PVC and the six most harmful phthalates. 183 × 61 × 0.6cm with a dual-layer non-slip texture that grips even in heat.\n\nLightweight at 900g with an elastic carry strap. Wipe clean with a damp cloth.' },
  { name: 'Official Size 5 Match Football — Hand-Stitched', cat: 'football', brand: 'Adidas', price: 349, compare: 449, stock: 52, weight: 0.45, tags: 'football,soccer,ball,sports',
    short: 'FIFA Basic quality, 32-panel hand-stitched TPU cover.',
    desc: 'A durable size 5 match ball with a hand-stitched TPU cover, 32 panels, butyl bladder for air retention and a 3mm foam backing for consistent flight.\n\nSuitable for grass and artificial turf. Ships partially inflated.' },
  { name: 'Black Stars Home Jersey 2025/26 — Replica', cat: 'football', brand: 'Biahens Select', price: 289, compare: 380, stock: 77, weight: 0.25, tags: 'jersey,black stars,football,ghana',
    short: 'Breathable replica jersey with the national crest.',
    desc: 'A fan replica of the Black Stars home kit: 100% recycled polyester interlock with moisture-wicking finish, embroidered crest, heat-transfer number and a ribbed crew neck.\n\nSizes S–XXL. Machine wash cold, do not iron prints.' },
  { name: '4-Person Dome Camping Tent — Waterproof', cat: 'camping', brand: 'Biahens Select', price: 899, compare: 1150, stock: 12, weight: 4.6, tags: 'tent,camping,outdoor,waterproof',
    short: '3000mm hydrostatic head, full rainfly and a 10-minute pitch.',
    desc: 'A four-person dome tent with 190T polyester walls, a 3000mm hydrostatic-head rainfly, taped seams and a bathtub-style PE floor.\n\nTwo doors, mesh inner panels for ventilation and insect protection, three internal pockets and a gear loft. Packs to 60 × 18cm and pitches in about 10 minutes.' },

  // ------------------------------------------------ Auto & Tools
  { name: 'Bosch 13mm 750W Impact Drill with 100-Piece Accessory Set', cat: 'tools', brand: 'Bosch', price: 1149, compare: 1399, stock: 20, weight: 3.4, tags: 'drill,bosch,tools,impact',
    short: '750W impact drill plus 100 bits, sockets and a carry case.',
    desc: 'A 750W impact drill with a 13mm keyed chuck, variable speed, forward/reverse and 48,000 impacts per minute in masonry.\n\nThe 100-piece set includes HSS drill bits, masonry bits, wood bits, screwdriver bits, sockets, a spirit level, hammer, pliers, measuring tape and a moulded case. 1-year Bosch warranty.' },
  { name: 'Total Tools 115-Piece Household Tool Kit', cat: 'tools', brand: 'Total Tools', price: 649, compare: 799, stock: 34, weight: 5.1, tags: 'tool kit,total tools,household,tools',
    short: 'Everything for home repairs in a blow-moulded case.',
    desc: '115 pieces: claw hammer, combination pliers, long-nose pliers, adjustable wrench, 8-piece hex key set, precision screwdriver set, utility knife, tape measure, spirit level, bit set, socket set and a durable blow-moulded case.' },
  { name: '12V Car Jump Starter + Power Bank 12,000mAh', cat: 'car-accessories', brand: 'Biahens Select', price: 749, compare: 949, stock: 28, weight: 0.9, tags: 'jump starter,car,power bank,emergency',
    short: 'Starts a dead battery in seconds and charges your phone too.',
    desc: '12,000mAh lithium pack delivering 600A peak current — enough to start petrol engines up to 5.0L and diesels up to 3.0L.\n\nAlso works as a power bank with USB-A and USB-C outputs, and doubles as a flashlight with SOS mode. Includes smart jumper clamps with reverse-polarity and short-circuit protection.' },
  { name: 'Motorcycle Helmet — DOT Certified Full Face (L)', cat: 'motorbike', brand: 'Biahens Select', price: 429, compare: 549, stock: 41, weight: 1.6, tags: 'helmet,motorcycle,safety,dot',
    short: 'DOT-approved full-face helmet with a scratch-resistant visor.',
    desc: 'Injection-moulded ABS shell with multi-density EPS liner, removable washable cheek pads, quick-release buckle and a scratch-resistant clear visor.\n\nDOT FMVSS 218 certified. Weighs 1.45kg. Sizes M, L and XL — measure your head 2cm above the brows.' },
  { name: '300W Solar Panel Kit with Charge Controller', cat: 'solar-generators', brand: 'Biahens Select', price: 2199, compare: 2699, stock: 10, weight: 22, tags: 'solar,panel,off grid,energy',
    short: 'Two 150W mono panels, 30A MPPT controller and mounting brackets.',
    desc: 'A complete off-grid starter kit: two 150W monocrystalline panels (21.5% cell efficiency), a 30A MPPT charge controller with LCD, 10m of solar cable, MC4 connectors and aluminium mounting brackets.\n\nEnough to keep a 200Ah battery bank topped for lighting, TV and phone charging. Battery and inverter sold separately.' },

  // ------------------------------------------------ Books & Stationery
  { name: 'Ghana Senior High School Core Mathematics Workbook', cat: 'books', brand: 'Sedco Publishing', price: 95, compare: 120, stock: 140, weight: 0.6, tags: 'book,education,maths,shs',
    short: 'WAEC-aligned Core Maths practice with worked solutions.',
    desc: 'A comprehensive Core Mathematics workbook aligned to the GES/WAEC syllabus, with worked examples, end-of-chapter exercises and full solutions to past questions from 2015–2024.\n\nPaperback, 480 pages, printed in Accra on 70gsm paper.' },
  { name: 'Things Fall Apart — Chinua Achebe (Penguin Classics)', cat: 'books', brand: 'Sedco Publishing', price: 119, compare: 145, stock: 88, weight: 0.28, tags: 'book,novel,african literature,classic',
    short: 'The classic African novel, Penguin Modern Classics edition.',
    desc: 'Chinua Achebe’s landmark novel about Okonkwo and the arrival of colonialism in Igboland. This Penguin Modern Classics paperback includes a biographical note and map.\n\n209 pages. Essential reading for SHS literature students and anyone building an African library.' },
  { name: 'A4 Exercise Book 120 Pages — Pack of 12', cat: 'school-supplies', brand: 'Biahens Select', price: 89, compare: 115, stock: 175, weight: 3.2, tags: 'exercise book,school,stationery,back to school',
    short: 'Twelve single-line A4 exercise books, 120 pages each.',
    desc: 'A full-term supply: twelve A4 exercise books with 120 pages of 60gsm paper, single-line ruling, stitched binding and a laminated cover that survives a school bag.\n\nBulk packs of 24 and 48 available — message us for a quote.' },
  { name: 'Executive Desk Organizer — Bamboo 7-Compartment', cat: 'office-supplies', brand: 'Biahens Select', price: 329, compare: 419, stock: 29, weight: 1.3, tags: 'desk organizer,office,bamboo,storage',
    short: 'Seven bamboo compartments with a phone slot and drawer.',
    desc: 'Sustainably harvested bamboo organiser with pen cups, a letter tray, business card slots, a phone stand and a shallow drawer.\n\n32 × 22 × 12cm, finished with a water-resistant lacquer and felt feet.' },
  { name: 'A3 Colour Laser Presentation Printer — Office', cat: 'printers', brand: 'HP', price: 15999, compare: 17999, stock: 3, weight: 32, tags: 'printer,office,a3,laser',
    short: 'A3 colour laser with duplex, network printing and 45ppm output.',
    desc: 'A heavy-duty A3 colour laser printer for busy offices and print shops: up to 45 pages per minute in colour and mono, automatic duplex, 1GB memory, gigabit Ethernet and Wi-Fi.\n\nTwo 550-sheet trays plus a 100-sheet multipurpose tray. 60,000-page monthly duty cycle.' },
];

const SLIDES = [
  { title: 'Mega Electronics Sale', subtitle: 'Up to 35% off TVs, laptops, phones and audio — free Accra delivery on orders above GH₵1,500.', badge: 'Up to 35% OFF', link_text: 'Shop electronics', link_url: '/c/electronics', bg: 'linear-gradient(115deg,#0F2A43 0%,#1E5C7A 55%,#2E86AB 100%)' },
  { title: 'New Season, New Look', subtitle: 'Ankara, kente and contemporary streetwear — cut and sewn in Accra.', badge: 'FASHION WEEK', link_text: 'Explore fashion', link_url: '/c/fashion', bg: 'linear-gradient(115deg,#2B1520 0%,#6E2B45 60%,#C2476B 100%)' },
  { title: 'Home & Kitchen Deals', subtitle: 'Fridges, air fryers, cookware and furniture with installation in Greater Accra.', badge: 'SAVE UP TO GH₵1,200', link_text: 'Shop home deals', link_url: '/c/home-kitchen', bg: 'linear-gradient(115deg,#08281F 0%,#14624A 60%,#2FA37C 100%)' },
  { title: 'Pay with MoMo or Card', subtitle: 'MTN, Telecel and AT Money accepted. Secure checkout, 7-day returns, real human support.', badge: 'FAST · SECURE', link_text: 'Start shopping', link_url: '/deals', bg: 'linear-gradient(115deg,#2A1F0B 0%,#7A5B1E 55%,#F26B21 100%)' },
];

const COUPONS = [
  { code: 'AKWAABA', description: 'GH₵50 off your first order over GH₵300', type: 'fixed', value: 50, min_subtotal: 300, usage_limit: 500, scope: 'all' },
  { code: 'WELCOME10', description: '10% off any order — new customers', type: 'percent', value: 10, max_discount: 250, min_subtotal: 0, usage_limit: 1000, scope: 'all' },
  { code: 'FREESHIP', description: 'Free standard delivery on orders above GH₵800', type: 'free_shipping', value: 0, min_subtotal: 800, usage_limit: 300, scope: 'all' },
  { code: 'PHONE25', description: 'GH₵250 off any smartphone above GH₵3,000', type: 'fixed', value: 250, min_subtotal: 3000, usage_limit: 100, scope: 'category', scope_slug: 'phones-tablets' },
  { code: 'KENTE15', description: '15% off fashion & traditional wear (max GH₵400)', type: 'percent', value: 15, max_discount: 400, min_subtotal: 200, usage_limit: 200, scope: 'category', scope_slug: 'fashion' },
  { code: 'EXPIRED5', description: 'Expired campaign code (for testing)', type: 'percent', value: 5, min_subtotal: 0, usage_limit: 50, scope: 'all', expires_in_days: -3 },
];

const SHIPPING_ZONES = [
  { region: 'Greater Accra', fee: 0, eta_days: 'Same day – 1 day', sort_order: 1 },
  { region: 'Tema', fee: 0, eta_days: 'Same day – 1 day', sort_order: 2 },
  { region: 'Ashanti', fee: 40, eta_days: '1–2 days', sort_order: 3 },
  { region: 'Central', fee: 35, eta_days: '1–2 days', sort_order: 4 },
  { region: 'Eastern', fee: 40, eta_days: '1–3 days', sort_order: 5 },
  { region: 'Western', fee: 55, eta_days: '2–3 days', sort_order: 6 },
  { region: 'Western North', fee: 60, eta_days: '2–4 days', sort_order: 7 },
  { region: 'Volta', fee: 50, eta_days: '2–3 days', sort_order: 8 },
  { region: 'Oti', fee: 65, eta_days: '3–4 days', sort_order: 9 },
  { region: 'Bono', fee: 60, eta_days: '2–4 days', sort_order: 10 },
  { region: 'Bono East', fee: 55, eta_days: '2–4 days', sort_order: 11 },
  { region: 'Ahafo', fee: 60, eta_days: '3–4 days', sort_order: 12 },
  { region: 'Northern', fee: 75, eta_days: '3–5 days', sort_order: 13 },
  { region: 'Savannah', fee: 80, eta_days: '3–5 days', sort_order: 14 },
  { region: 'North East', fee: 85, eta_days: '4–6 days', sort_order: 15 },
  { region: 'Upper East', fee: 85, eta_days: '4–6 days', sort_order: 16 },
  { region: 'Upper West', fee: 90, eta_days: '4–6 days', sort_order: 17 },
];

module.exports = { CATEGORIES, BRANDS, PRODUCTS, SLIDES, COUPONS, SHIPPING_ZONES };
